version: '3.5'

services:
  rescope.build:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  rescope.test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: dotnet test -c Release --no-build
